name: CI
on: [push,pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependences
        run: npm install
      - name: Build front
        run: npm run build
      - name: Run tests
        run: npm test